### ISSUE TITLE
reflex doesn't compile with 9.6.1

### ISSUE THREAD

**Issue by GeorgeCo** [reflex-frp/reflex#491]
```
src/Reflex/Class.hs:237:9: error: [GHC-76037]
    Not in scope: type constructor or class ‘MonadFix’
    Suggested fix: Perhaps use ‘MonadFail’ (imported from Prelude)
    |
237 |       , MonadFix (PushM t)
    |         ^^^^^^^^
```

**Comment by alexfmpe** [comment]
See #492

**Comment by ali-abrar** [comment]
fixed in v0.9.0.1
