### PR TITLE
Minimal support for 9.10

### PR DESCRIPTION
**Pull request by Ericson2314**
PR #502 contains some other orthogonal cleanups.

### CODE REVIEW

**Comment by Ericson2314** [comment]
I see @ymeister fixed the build in https://github.com/reflex-frp/reflex/pull/502, but I don't get why 9.10 is no longer accepting constraints as written.

**Comment by ymeister** [comment]
> ```
> src/Reflex/PerformEvent/Base.hs:76:10: error: [GHC-39999]
> Error:     • Could not deduce ‘Monad (HostFrame t)’
>         arising from the superclasses of an instance declaration
>       from the context: (ReflexHost t, Ref m ~ Ref IO)
>         bound by the instance declaration
>         at src/Reflex/PerformEvent/Base.hs:76:10-77
>       Possible fix:
>         If the constraint looks soluble from a superclass of the instance context,
>         read 'Undecidable instances and loopy superclasses' in the user manual
>     • In the instance declaration for
>         ‘PerformEvent t (PerformEventT t m)’
>    |
> 76 | instance (ReflexHost t, Ref m ~ Ref IO) => PerformEvent t (PerformEventT t m) where
>    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> Note that `ReflexClass` looks like this
> 
> ```haskell
> class ( Reflex t
>       , MonadReflexCreateTrigger t (HostFrame t)
>       , MonadSample t (HostFrame t)
>       , MonadHold t (HostFrame t)
>       , MonadFix (HostFrame t)
>       , MonadSubscribeEvent t (HostFrame t)
>       ) => ReflexHost t where
> ```
> 
> I see @ymeister fixed the build in #502, but I don't get why 9.10 is no longer accepting constraints as written.

It might be due to this - https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0287-simplify-subsumption.rst

> GHC 9.0 made a switch to a type inference scheme for higher rank polymorphism called [simplified subsumption](https://github.com/ghc-proposals/ghc-proposals/pull/287). Consquently, expressions like g f in the below, which passed the type checker in the GHC 8 series, stopped passing the type checker in the GHC 9 series.

```
{-# LANGUAGE RankNTypes #-}

f :: Int -> (forall a. a -> a)
f _ = id

g :: (forall a. Int -> a -> a) -> ()
g _ = ()

main :: IO ()
main = print (g f)
```

**Comment by maralorn** [comment]
I don't think anything related to simplified subsumption changed from 9.8 to 9.10. At least the big breaking change was much earlier.

**Comment by Ericson2314** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/25318 I made a GHC issue on this for hopefully better visibility to get to the bottom of it.

**Comment by Ericson2314** [comment]
See the GHC issue I linked, this typechecker change is intentional

> If the constraint looks soluble from a superclass of the instance context,
> read 'Undecidable instances and loopy superclasses' in the user manual

and 🤦 that bit in the type error did indeed tell me exactly what to do.
